version: '3.7'
services:
   backend:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: chat
    restart: always
    ports:
    - 8080:8080
    depends_on:
      - rabbitmq
    network_mode: "host"
        
   rabbitmq:
    build:
     context: .
     dockerfile: ./Dockerfile2
    container_name: rabbitmq
    
    restart: always
    expose:
    - "5672" 
    - "15672" 
    - "61613"
    ports:
     - "5672:5672" 
     - "15672:15672" 
     - "61613:61613"